# Generated by Django 2.0.6 on 2019-02-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='OwnUser',
        ),
    ]
