# Generated by Django 2.0.6 on 2019-02-22 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20190222_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownuser',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
