# Generated by Django 2.0.6 on 2019-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_ownuser_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ownuser',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6),
        ),
    ]
