# Generated by Django 2.0.6 on 2019-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20190222_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
