# Generated by Django 2.0.6 on 2019-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_auto_20190222_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
