# Generated by Django 2.0.6 on 2019-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0007_auto_20190222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
